import type { FormSchema } from "../form-engine/types/index.js";

/**
 * Business Starter Package Form Schema
 *
 * এই schema টি BanglaBiz Business Starter Package application form এর জন্য।
 * 6 টি step আছে:
 * 1. General & Office
 * 2. Capital & Share
 * 3. Subscriber Info (Repeatable Directors)
 * 4. Witness Info
 * 5. Additional Information
 * 6. Summary / Preview
 */

export const businessStarterPackageSchema: FormSchema = {
  title: "Business Starter Package Application",
  description: "Complete application form for Business Starter Package",

  // Centralized upload configuration
  uploadSources: [
    {
      id: "business-document-upload",
      url: "https://api.example.com/upload/business-documents",
      method: "POST",
      headers: {
        Authorization: "Bearer your-token-here",
      },
      fieldName: "file",
      additionalData: {
        folder: "business-starter-package",
        category: "documents",
      },
      transform: (response) => response.data?.fileUrl || response.url,
    },
    {
      id: "business-image-upload",
      url: "https://api.example.com/upload/business-images",
      method: "POST",
      headers: {
        Authorization: "Bearer your-token-here",
      },
      fieldName: "image",
      additionalData: {
        folder: "business-starter-package",
        category: "photos",
      },
      transform: (response) => response.data?.imageUrl || response.url,
    },
  ],

  steps: [
    // Step 1: General & Office
    {
      title: "General & Office",
      description: "Company general information and office address",
      className: "bg-white",
      sections: [
        {
          title: "General Information",
          fields: [
            {
              name: "company_name",
              label: "Company Name",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "ABC Trading Company Ltd.",
              validation: {
                required: true,
                minLength: 2,
                maxLength: 200,
              },
            },
            {
              name: "entity_type",
              label: "Entity Type",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "private_limited",
              validation: {
                required: true,
              },
              options: [
                { label: "Proprietorship", value: "proprietorship" },
                { label: "Partnership", value: "partnership" },
                { label: "Private Limited Company", value: "private_limited" },
                { label: "Public Limited Company", value: "public_limited" },
                { label: "One Person Company", value: "one_person_company" },
              ],
            },
            {
              name: "main_business_objective",
              label: "Main Business Objective",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue:
                "Import, export and trading of general merchandise and consumer goods",
              validation: {
                required: true,
                minLength: 10,
                maxLength: 500,
              },
            },
            {
              name: "business_sector",
              label: "Business Sector",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "retail",
              validation: {
                required: true,
              },
              options: [
                { label: "Agriculture", value: "agriculture" },
                { label: "Manufacturing", value: "manufacturing" },
                { label: "Information Technology", value: "technology" },
                { label: "Healthcare", value: "healthcare" },
                { label: "Education", value: "education" },
                { label: "Finance & Banking", value: "finance" },
                { label: "Retail & E-commerce", value: "retail" },
                { label: "Construction", value: "construction" },
                { label: "Hospitality & Tourism", value: "hospitality" },
                {
                  label: "Transportation & Logistics",
                  value: "transportation",
                },
                { label: "Energy & Utilities", value: "energy" },
                { label: "Telecommunications", value: "telecom" },
              ],
            },
            {
              name: "business_sub_sector",
              label: "Business Sub-Sector",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "trading",
              validation: {
                required: true,
              },
              options: [
                { label: "Manufacturing", value: "manufacturing" },
                { label: "Trading", value: "trading" },
                { label: "Service", value: "service" },
                { label: "Agriculture", value: "agriculture" },
                { label: "Technology", value: "technology" },
              ],
            },
            {
              name: "entity_email_address",
              label: "Entity Email Address",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "info@abctrading.com",
              validation: {
                required: true,
                pattern: {
                  value: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
                  message: "Please enter a valid email address",
                },
              },
            },
          ],
        },
        {
          title: "Office Address",
          fields: [
            {
              name: "division",
              label: "Division",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "dhaka",
              validation: {
                required: true,
              },
              clearFields: ["district", "police_station"],
              options: [
                { label: "Dhaka", value: "dhaka" },
                { label: "Chittagong", value: "chittagong" },
                { label: "Rajshahi", value: "rajshahi" },
                { label: "Khulna", value: "khulna" },
                { label: "Barisal", value: "barisal" },
                { label: "Sylhet", value: "sylhet" },
                { label: "Rangpur", value: "rangpur" },
                { label: "Mymensingh", value: "mymensingh" },
              ],
            },
            {
              name: "district",
              label: "District",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "dhaka",
              validation: {
                required: true,
              },
              clearFields: ["police_station"],
              enableWhen: {
                field: "division",
                isNotEmpty: true,
              },
              options: [
                { label: "Dhaka", value: "dhaka" },
                { label: "Chittagong", value: "chittagong" },
                { label: "Sylhet", value: "sylhet" },
                { label: "Rajshahi", value: "rajshahi" },
                { label: "Khulna", value: "khulna" },
                { label: "Barisal", value: "barisal" },
                { label: "Rangpur", value: "rangpur" },
                { label: "Mymensingh", value: "mymensingh" },
              ],
            },
            {
              name: "police_station",
              label: "Police Station",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "gulshan",
              validation: {
                required: true,
              },
              enableWhen: {
                field: "district",
                isNotEmpty: true,
              },
              options: [
                { label: "Dhaka Metropolitan", value: "dhaka_metro" },
                { label: "Mirpur Model", value: "mirpur_model" },
                { label: "Gulshan", value: "gulshan" },
                { label: "Uttara", value: "uttara" },
                { label: "Dhanmondi", value: "dhanmondi" },
              ],
            },
            {
              name: "post_code",
              label: "Post Code",
              type: "number",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "1212",
              maxLength: 4,
              validation: {
                required: true,
                minLength: {
                  value: 4,
                  message: "Post code must be 4 digits",
                },
              },
            },
            {
              name: "zone_circle",
              label: "Zone / Circle",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "zone_1",
              validation: {
                required: true,
              },
              options: [
                { label: "Zone 1", value: "zone_1" },
                { label: "Zone 2", value: "zone_2" },
                { label: "Zone 3", value: "zone_3" },
                { label: "Zone 4", value: "zone_4" },
                { label: "Zone 5", value: "zone_5" },
              ],
            },
            {
              name: "ward",
              label: "Ward",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "ward_1",
              validation: {
                required: true,
              },
              options: [
                { label: "Ward 1", value: "ward_1" },
                { label: "Ward 2", value: "ward_2" },
                { label: "Ward 3", value: "ward_3" },
                { label: "Ward 4", value: "ward_4" },
                { label: "Ward 5", value: "ward_5" },
              ],
            },
            {
              name: "sector_section",
              label: "Sector / Section",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "sector_1",
              validation: {
                required: true,
              },
              options: [
                { label: "Sector 1", value: "sector_1" },
                { label: "Sector 2", value: "sector_2" },
                { label: "Sector 3", value: "sector_3" },
                { label: "Sector 4", value: "sector_4" },
                { label: "Sector 5", value: "sector_5" },
              ],
            },
            {
              name: "area_block",
              label: "Area / Block",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "block_a",
              validation: {
                required: true,
              },
              options: [
                { label: "Block A", value: "block_a" },
                { label: "Block B", value: "block_b" },
                { label: "Block C", value: "block_c" },
                { label: "Block D", value: "block_d" },
                { label: "Block E", value: "block_e" },
              ],
            },
            {
              name: "road",
              label: "Road",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "road_1",
              validation: {
                required: true,
              },
              options: [
                { label: "Road 1", value: "road_1" },
                { label: "Road 2", value: "road_2" },
                { label: "Road 3", value: "road_3" },
                { label: "Road 4", value: "road_4" },
                { label: "Road 5", value: "road_5" },
              ],
            },
            {
              name: "address",
              label: "Address",
              type: "text",
              placeholder: "Address",
              cols: 1,
              defaultValue: "House 12, Road 1, Gulshan-1, Dhaka",
              validation: {
                required: true,
                minLength: 10,
                maxLength: 500,
              },
            },
            {
              name: "place_of_business",
              label: "Place of Business (Rent/Own)",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "rent",
              validation: {
                required: true,
              },
              options: [
                { label: "Rent", value: "rent" },
                { label: "Own", value: "own" },
              ],
            },
            {
              name: "sign_board_sqft",
              label: "Sign Board Sq. ft.",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "10_to_20",
              validation: {
                required: true,
              },
              options: [
                { label: "Less than 10 sq. ft.", value: "less_than_10" },
                { label: "10-20 sq. ft.", value: "10_to_20" },
                { label: "20-30 sq. ft.", value: "20_to_30" },
                { label: "30-50 sq. ft.", value: "30_to_50" },
                { label: "More than 50 sq. ft.", value: "more_than_50" },
              ],
            },
          ],
        },
      ],
    },

    // Step 2: Capital & Share
    {
      title: "Capital & Share",
      description: "Share capital and director information",
      fields: [
        {
          name: "number_of_shares",
          label: "Number of Shares",
          type: "number",
          placeholder: "0",
          cols: 1,
          validation: {
            required: true,
            min: 1,
            max: 99999999,
          },
        },
        {
          name: "number_of_qualification_shares",
          label: "Number of Qualification Shares",
          type: "number",
          placeholder: "0",
          cols: 1,
          defaultValue: 100,
          validation: {
            required: true,
            min: 1,
            max: 99999999,
          },
        },
        {
          name: "minimum_no_of_directors",
          label: "Minimum No. of Directors",
          type: "number",
          placeholder: "0",
          cols: 1,
          defaultValue: 3,
          validation: {
            required: true,
            min: 1,
            max: 100,
          },
        },
        {
          name: "maximum_no_of_directors",
          label: "Maximum No. of Directors",
          type: "number",
          placeholder: "0",
          cols: 1,
          defaultValue: 12,
          validation: {
            required: true,
            min: 1,
            max: 100,
          },
        },
        {
          name: "quorum_of_agm_egm",
          label: "Quorum of AGM/EGM",
          type: "number",
          placeholder: "0",
          cols: 1,
          defaultValue: 2,
          validation: {
            required: true,
            min: 1,
            max: 100,
          },
        },
        {
          name: "quorum_of_board_meeting",
          label: "Quorum of Board of Directors' Meeting",
          type: "number",
          placeholder: "0",
          cols: 1,
          defaultValue: 2,
          validation: {
            required: true,
            min: 1,
            max: 100,
          },
        },
        {
          name: "duration_for_chairmanship",
          label: "Duration for Chairmanship (year)",
          type: "number",
          placeholder: "0",
          cols: 1,
          defaultValue: 3,
          validation: {
            required: true,
            min: 1,
            max: 50,
          },
        },
        {
          name: "duration_for_managing_directorship",
          label: "Duration for Managing Directorship (year)",
          type: "number",
          placeholder: "0",
          cols: 1,
          defaultValue: 5,
          validation: {
            required: true,
            min: 1,
            max: 50,
          },
        },
      ],
    },

    // Step 3: Subscriber Info (Directors - Repeatable)
    {
      title: "Subscriber Info",
      description: "Add director/subscriber information",
      sections: [
        {
          title: "Directors",
          description: "Add all directors and their information",
          repeatable: true,
          repeatableConfig: {
            addButtonText: "➕ Add New Director",
            removeButtonText: "✕ Remove",
            minItems: 1,
            maxItems: 10,
          },
          fields: [
            {
              name: "director_name",
              label: "Name",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "John Doe",
              validation: {
                required: true,
                minLength: 2,
                maxLength: 100,
              },
            },
            {
              name: "director_position",
              label: "Position",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "director",
              validation: {
                required: true,
              },
              options: [
                { label: "Chairman", value: "chairman" },
                { label: "Managing Director", value: "managing_director" },
                { label: "Director", value: "director" },
                { label: "Executive Director", value: "executive_director" },
              ],
            },
            {
              name: "director_subscribed_shares",
              label: "Number of Subscribed Shares",
              type: "number",
              placeholder: "0",
              cols: 1,
              defaultValue: 100,
              validation: {
                required: true,
                min: 1,
                max: 99999999,
              },
            },
            {
              name: "director_nationality",
              label: "Nationality",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "bangladeshi",
              validation: {
                required: true,
              },
              options: [
                { label: "Bangladeshi", value: "bangladeshi" },
                { label: "Indian", value: "indian" },
                { label: "American", value: "american" },
                { label: "British", value: "british" },
                { label: "Other", value: "other" },
              ],
            },
            {
              name: "director_nid_passport",
              label: "NID/Passport Number",
              type: "number",
              placeholder: "Enter NID or Passport number",
              cols: 1,
              defaultValue: "1234567890",
              maxLength: 20,
              validation: {
                required: true,
                minLength: {
                  value: 8,
                  message: "NID/Passport must be at least 8 digits",
                },
              },
            },
            {
              name: "director_nid_passport_type",
              label: "ID Type",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "nid",
              options: [
                { label: "NID", value: "nid" },
                { label: "Passport", value: "passport" },
              ],
            },
            {
              name: "director_tin",
              label: "TIN",
              type: "number",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "123456789012",
              maxLength: 12,
              validation: {
                required: true,
                minLength: {
                  value: 12,
                  message: "TIN must be 12 digits",
                },
              },
            },
            {
              name: "director_father_name",
              label: "Father's Name",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "Michael Doe",
              validation: {
                required: true,
                minLength: 2,
                maxLength: 100,
              },
            },
            {
              name: "director_mother_name",
              label: "Mother's Name",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "Sarah Doe",
              validation: {
                required: true,
                minLength: 2,
                maxLength: 100,
              },
            },
            {
              name: "director_current_address",
              label: "Current Address",
              type: "text",
              placeholder: "Address",
              cols: 1,
              defaultValue: "House 25, Road 5, Dhanmondi, Dhaka",
              validation: {
                required: true,
                minLength: 10,
                maxLength: 500,
              },
            },
            {
              name: "director_current_district",
              label: "District of Current Address",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "dhaka",
              validation: {
                required: true,
              },
              options: [
                { label: "Dhaka", value: "dhaka" },
                { label: "Chittagong", value: "chittagong" },
                { label: "Sylhet", value: "sylhet" },
                { label: "Rajshahi", value: "rajshahi" },
                { label: "Khulna", value: "khulna" },
                { label: "Barisal", value: "barisal" },
                { label: "Rangpur", value: "rangpur" },
                { label: "Mymensingh", value: "mymensingh" },
              ],
            },
            {
              name: "director_permanent_address",
              label: "Permanent Address",
              type: "text",
              placeholder: "Address",
              cols: 1,
              defaultValue: "Village: Rampur, Post: Mirzapur, Tangail",
              validation: {
                required: true,
                minLength: 10,
                maxLength: 500,
              },
            },
            {
              name: "director_permanent_district",
              label: "District of Permanent Address",
              type: "select",
              placeholder: "Select One",
              cols: 1,
              defaultValue: "dhaka",
              validation: {
                required: true,
              },
              options: [
                { label: "Dhaka", value: "dhaka" },
                { label: "Chittagong", value: "chittagong" },
                { label: "Sylhet", value: "sylhet" },
                { label: "Rajshahi", value: "rajshahi" },
                { label: "Khulna", value: "khulna" },
                { label: "Barisal", value: "barisal" },
                { label: "Rangpur", value: "rangpur" },
                { label: "Mymensingh", value: "mymensingh" },
              ],
            },
            {
              name: "director_email",
              label: "Email",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "john.doe@example.com",
              validation: {
                required: true,
                pattern: {
                  value: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
                  message: "Please enter a valid email address",
                },
              },
            },
            {
              name: "director_date_of_birth",
              label: "Date of Birth",
              type: "date",
              placeholder: "DD-MM-YYYY",
              cols: 1,
              defaultValue: "1985-01-15",
              validation: {
                required: true,
              },
            },
            {
              name: "is_principal_promoter",
              label: "Principal Promoter",
              type: "checkbox",
              checkboxLabel: "This Director is also a Principal Promoter",
              cols: 2,
              defaultValue: false,
            },
          ],
        },
        {
          title: "Necessary Document Attachments",
          fields: [
            {
              name: "principal_promoter_nid_passport",
              label: "Principal Promoter's NID/Passport",
              type: "file",
              accept: ".pdf,.jpg,.jpeg,.png",
              uploadSourceId: "business-document-upload",
              cols: 1,
              validation: {
                required: true,
              },
            },
            {
              name: "principal_promoter_photo",
              label: "Principal Promoter's Photo",
              type: "file",
              accept: ".jpg,.jpeg,.png",
              uploadSourceId: "business-image-upload",
              cols: 1,
            },
          ],
        },
      ],
    },

    // Step 4: Witness Info
    {
      title: "Witness Info",
      description: "Provide witness information",
      sections: [
        {
          title: "Witness 1",
          fields: [
            {
              name: "witness1_name",
              label: "Name",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "Alice Johnson",
              validation: {
                required: true,
                minLength: 2,
                maxLength: 100,
              },
            },
            {
              name: "witness1_address",
              label: "Address",
              type: "text",
              placeholder: "Address",
              cols: 1,
              defaultValue: "House 45, Road 12, Banani, Dhaka",
              validation: {
                required: true,
                minLength: 10,
                maxLength: 500,
              },
            },
            {
              name: "witness1_phone",
              label: "Phone",
              type: "phone",
              placeholder: "Enter phone number",
              cols: 1,
              defaultValue: "+8801712345678",
              defaultCountry: "bd",
              validation: {
                required: true,
              },
            },
            {
              name: "witness1_nid",
              label: "NID",
              type: "number",
              placeholder: "XXXXXXXXXXX",
              cols: 1,
              defaultValue: "9876543210",
              maxLength: 17,
              validation: {
                required: true,
                minLength: {
                  value: 10,
                  message: "NID must be at least 10 digits",
                },
              },
            },
          ],
        },
        {
          title: "Witness 2",
          fields: [
            {
              name: "witness2_name",
              label: "Name",
              type: "text",
              placeholder: "Enter",
              cols: 1,
              defaultValue: "Robert Smith",
              validation: {
                required: true,
                minLength: 2,
                maxLength: 100,
              },
            },
            {
              name: "witness2_address",
              label: "Address",
              type: "text",
              placeholder: "Address",
              cols: 1,
              defaultValue: "Flat 3B, House 78, Road 27, Dhanmondi, Dhaka",
              validation: {
                required: true,
                minLength: 10,
                maxLength: 500,
              },
            },
            {
              name: "witness2_phone",
              label: "Phone",
              type: "phone",
              placeholder: "Enter phone number",
              cols: 1,
              defaultValue: "+8801798765432",
              defaultCountry: "bd",
              validation: {
                required: true,
              },
            },
            {
              name: "witness2_nid",
              label: "NID",
              type: "number",
              placeholder: "XXXXXXXXXXX",
              cols: 1,
              defaultValue: "1234509876",
              maxLength: 17,
              validation: {
                required: true,
                minLength: {
                  value: 10,
                  message: "NID must be at least 10 digits",
                },
              },
            },
          ],
        },
      ],
    },

    // Step 5: Applicant Info
    {
      title: "Applicant Info",
      description: "Information about the applicant",
      fields: [
        {
          name: "applicant_name",
          label: "Name",
          type: "text",
          placeholder: "Enter",
          cols: 1,
          defaultValue: "James Anderson",
          validation: {
            required: true,
            minLength: 2,
            maxLength: 100,
          },
        },
        {
          name: "applicant_position",
          label: "Position",
          type: "select",
          placeholder: "Select One",
          cols: 1,
          defaultValue: "director",
          validation: {
            required: true,
          },
          options: [
            { label: "Chairman", value: "chairman" },
            { label: "Managing Director", value: "managing_director" },
            { label: "Director", value: "director" },
            { label: "Executive Director", value: "executive_director" },
            { label: "Advocate", value: "advocate" },
            { label: "Company Secretary", value: "company_secretary" },
          ],
        },
        {
          name: "applicant_current_address",
          label: "Current Address",
          type: "text",
          placeholder: "Address",
          cols: 1,
          defaultValue: "Apartment 5C, House 99, Road 11, Baridhara, Dhaka",
          validation: {
            required: true,
            minLength: 10,
            maxLength: 500,
          },
        },
        {
          name: "applicant_current_district",
          label: "District of Current Address",
          type: "select",
          placeholder: "Select One",
          cols: 1,
          defaultValue: "dhaka",
          validation: {
            required: true,
          },
          options: [
            { label: "Dhaka", value: "dhaka" },
            { label: "Chittagong", value: "chittagong" },
            { label: "Sylhet", value: "sylhet" },
            { label: "Rajshahi", value: "rajshahi" },
            { label: "Khulna", value: "khulna" },
            { label: "Barisal", value: "barisal" },
            { label: "Rangpur", value: "rangpur" },
            { label: "Mymensingh", value: "mymensingh" },
          ],
        },
        {
          name: "applicant_father_name",
          label: "Father's Name",
          type: "text",
          placeholder: "Enter",
          cols: 1,
          defaultValue: "Robert Anderson",
          validation: {
            required: true,
            minLength: 2,
            maxLength: 100,
          },
        },
        {
          name: "applicant_mother_name",
          label: "Mother's Name",
          type: "text",
          placeholder: "Enter",
          cols: 1,
          defaultValue: "Mary Anderson",
          validation: {
            required: true,
            minLength: 2,
            maxLength: 100,
          },
        },
        {
          name: "applicant_division",
          label: "Division",
          type: "select",
          placeholder: "Select One",
          cols: 1,
          defaultValue: "dhaka",
          validation: {
            required: true,
          },
          options: [
            { label: "Dhaka", value: "dhaka" },
            { label: "Chittagong", value: "chittagong" },
            { label: "Rajshahi", value: "rajshahi" },
            { label: "Khulna", value: "khulna" },
            { label: "Barisal", value: "barisal" },
            { label: "Sylhet", value: "sylhet" },
            { label: "Rangpur", value: "rangpur" },
            { label: "Mymensingh", value: "mymensingh" },
          ],
        },
        {
          name: "applicant_district",
          label: "District",
          type: "select",
          placeholder: "Select One",
          cols: 1,
          defaultValue: "dhaka",
          validation: {
            required: true,
          },
          options: [
            { label: "Dhaka", value: "dhaka" },
            { label: "Chittagong", value: "chittagong" },
            { label: "Sylhet", value: "sylhet" },
            { label: "Rajshahi", value: "rajshahi" },
            { label: "Khulna", value: "khulna" },
            { label: "Barisal", value: "barisal" },
            { label: "Rangpur", value: "rangpur" },
            { label: "Mymensingh", value: "mymensingh" },
          ],
        },
        {
          name: "applicant_police_station",
          label: "Police Station",
          type: "select",
          placeholder: "Select One",
          cols: 1,
          defaultValue: "gulshan",
          validation: {
            required: true,
          },
          options: [
            { label: "Gulshan", value: "gulshan" },
            { label: "Banani", value: "banani" },
            { label: "Dhanmondi", value: "dhanmondi" },
            { label: "Mirpur", value: "mirpur" },
            { label: "Mohammadpur", value: "mohammadpur" },
            { label: "Uttara", value: "uttara" },
          ],
        },
        {
          name: "applicant_post_code",
          label: "Post Code",
          type: "number",
          placeholder: "0",
          cols: 1,
          defaultValue: 1212,
          validation: {
            required: true,
            min: 1000,
            max: 9999,
          },
        },
        {
          name: "applicant_village_mahalla",
          label: "Village/Mahalla",
          type: "text",
          placeholder: "Enter",
          cols: 1,
          defaultValue: "Gulshan-2",
          validation: {
            required: true,
            minLength: 2,
            maxLength: 100,
          },
        },
        {
          name: "applicant_permanent_address",
          label: "Permanent Address",
          type: "text",
          placeholder: "Address",
          cols: 1,
          defaultValue:
            "Village Sreepur, Post Office Sreepur, Gazipur District",
          validation: {
            required: true,
            minLength: 10,
            maxLength: 500,
          },
        },
      ],
    },

    // Step 6: Declared by
    {
      title: "Declared by",
      description: "Declaration information",
      fields: [
        {
          name: "declared_name",
          label: "Name",
          type: "text",
          placeholder: "Enter",
          cols: 1,
          defaultValue: "Michael Roberts",
          validation: {
            required: true,
            minLength: 2,
            maxLength: 100,
          },
        },
        {
          name: "declared_position",
          label: "Position",
          type: "select",
          placeholder: "Select One",
          cols: 1,
          defaultValue: "company_secretary",
          validation: {
            required: true,
          },
          options: [
            { label: "Chairman", value: "chairman" },
            { label: "Managing Director", value: "managing_director" },
            { label: "Director", value: "director" },
            { label: "Executive Director", value: "executive_director" },
            { label: "Advocate", value: "advocate" },
            { label: "Company Secretary", value: "company_secretary" },
          ],
        },
        {
          name: "declared_organization",
          label: "Organization (applicable for advocate only)",
          type: "text",
          placeholder: "Enter",
          cols: 1,
          defaultValue: "Professional Services Ltd.",
          validation: {
            minLength: 2,
            maxLength: 200,
          },
        },
        {
          name: "declared_address",
          label: "Address",
          type: "text",
          placeholder: "Address",
          cols: 1,
          defaultValue: "House 45, Road 8, Sector 4, Uttara, Dhaka-1230",
          validation: {
            required: true,
            minLength: 10,
            maxLength: 500,
          },
        },
      ],
    },
  ],
};
